# Generated by Django 4.2.16 on 2024-11-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('invite_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('activated_invite', models.CharField(blank=True, max_length=6, null=True)),
                ('referred_users', models.ManyToManyField(blank=True, to='referral.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
